In [1]:
import numpy as np
import pandas as pd
data=({
    "name":["abel","sara",None,"john"],
    "age":[20,np.nan,25,30],
    "salary":[4000,4500,5000,45000],
    "join_date":[
        "2026-01-01",
        "01/02/2026",
        "March 10,2026",
        "2026.04.15"]
})
df=pd.DataFrame(data)

In [2]:
df

   name   age  salary      join_date
0  abel  20.0    4000     2026-01-01
1  sara   NaN    4500     01/02/2026
2  None  25.0    5000  March 10,2026
3  john  30.0   45000     2026.04.15

In [3]:
df_cleaned = df.dropna()
print(df_cleaned)

   name   age  salary   join_date
0  abel  20.0    4000  2026-01-01
3  john  30.0   45000  2026.04.15

In [37]:
for column in df.columns:
 if df[column].dtype == 'float64' or df[column].dtype == 'int64':
  df[column].fillna(df[column].mean())
df["name"]=df["name"].fillna("unkown")
print(df)

     name   age  salary      join_date
0    abel  20.0    4000     2026-01-01
1    sara   NaN    4500     01/02/2026
2  unkown  25.0    5000  March 10,2026
3    john  30.0   45000     2026.04.15

In [5]:
from dateutil.parser import parse
def parse_date(date_str):
 try:
  return parse(date_str, dayfirst=False)
 except ValueError:
  return pd.NaT
df['join_date'] = df['join_date'].apply(parse_date)
df['join_date'] = df['join_date'].dt.strftime('%Y-%m-%d')
print("Result")
print(df)

Result
      name   age  salary   join_date
0     abel  20.0    4000  2026-01-01
1     sara   NaN    4500  2026-01-02
2  unkonwn  25.0    5000  2026-03-10
3     john  30.0   45000  2026-04-15

In [25]:
df = pd.DataFrame(data)
Q1 = df['salary'].quantile(0.25)
Q3 = df['salary'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df['Outlier Column'] = df['salary'].apply(lambda x: 'Outlier' if x > upper_bound else 'Normal')

In [10]:
Q3

np.float64(15000.0)

In [11]:
Q1

np.float64(4375.0)

In [13]:
lower_bound

np.float64(-11562.5)

In [14]:

upper_bound

np.float64(30937.5)

In [17]:
IQR

np.float64(10625.0)

In [26]:
Outliner

   name   age  salary   join_date
3  john  30.0   45000  2026.04.15